version: 2.1
 
references:
default_config: &default_config
  docker:
    - image: hashicorp/terraform:0.12.29
  working_directory: ~/project
  environment:
    TERRAFORM_ENV: ~/project/
 
repo_cache_key: &repo_cache_key v1-repo-{{ .Branch }}-{{ .Revision }}
 
restore_repo: &restore_repo
  restore_cache:
    key: *repo_cache_key
 
save_repo: &save_repo
  save_cache:
    key: *repo_cache_key
    paths:
      - ~/project
 
## stg
stg_set_terraform_environment: &stg_set_terraform_environment
  run:
    name: set terraform environment
    command: |
      mkdir -p ~/.aws
      echo "[stg-adachin-terraform]" > ~/.aws/credentials
      echo "aws_access_key_id = ${STG_TERRAFORM_AWS_ACCESS_KEY_ID}" >> ~/.aws/credentials
      echo "aws_secret_access_key = ${STG_TERRAFORM_AWS_SECRET_ACCESS_KEY}" >> ~/.aws/credentials
      echo "region = ap-northeast-1" >> ~/.aws/credentials
stg_terraform_init: &stg_terraform_init
  run:
    name: terraform init
    command: |
      cd ~/project/terraform/stg
      terraform init
 
## Prd
prd_set_terraform_environment: &prd_set_terraform_environment
  run:
    name: set terraform environment
    command: |
      mkdir -p ~/.aws
      echo "[prd-adachin-terraform]" > ~/.aws/credentials
      echo "aws_access_key_id = ${PRD_TERRAFORM_AWS_ACCESS_KEY_ID}" >> ~/.aws/credentials
      echo "aws_secret_access_key = ${PRD_TERRAFORM_AWS_SECRET_ACCESS_KEY}" >> ~/.aws/credentials
      echo "region = ap-northeast-1" >> ~/.aws/credentials
prd_terraform_init: &prd_terraform_init
  run:
    name: terraform init
    command: |
      cd ~/project/terraform/prd
      terraform init
 
jobs:
  stg_terraform_fmt_validate:
    <<: *default_config
    steps:
      - checkout
      - *stg_set_terraform_environment
      - run:
          name: terraform fmt validate
          command: |
            cd ~/project/terraform/stg
            terraform init -backend-config="profile=stg-adachin-terraform"
            terraform fmt
            terraform validate
      - *save_repo
 
  prd_terraform_fmt_validate:
    <<: *default_config
    steps:
      - checkout
      - *prd_set_terraform_environment
      - run:
          name: terraform fmt validate
          command: |
            cd ~/project/terraform/prd
            terraform init -backend-config="profile=prd-adachin-terraform"
            terraform fmt
            terraform validate
      - *save_repo
 
  stg_terraform_plan:
    <<: *default_config
    steps:
      - *restore_repo
      - *stg_set_terraform_environment
      - *stg_terraform_init
      - run:
          name: terraform plan
          command: |
            cd ~/project/terraform/stg
            terraform plan
 
  prd_terraform_plan:
    <<: *default_config
    steps:
      - *restore_repo
      - *prd_set_terraform_environment
      - *prd_terraform_init
      - run:
          name: terraform plan
          command: |
            cd ~/project/terraform/prd
            terraform plan
 
  stg_terraform_apply:
    <<: *default_config
    steps:
      - *restore_repo
      - *stg_set_terraform_environment
      - *stg_terraform_init
      - run:
          name: terraform apply
          command: |
            cd ~/project/terraform/stg
            terraform apply -auto-approve            
 
  prd_terraform_apply:
    <<: *default_config
    steps:
      - *restore_repo
      - *prd_set_terraform_environment
      - *prd_terraform_init
      - run:
          name: terraform apply
          command: |
            cd ~/project/terraform/prd
            terraform apply -auto-approve            
 
workflows:
  version: 2
  deploy:
    jobs:
      - stg_terraform_fmt_validate
      - stg_terraform_plan:
          requires:
            - stg_terraform_fmt_validate
      - stg_terraform_apply:
          filters:
            branches:
              only: master
          requires:
            - stg_terraform_plan
      - prd_terraform_fmt_validate
      - prd_terraform_plan:
          requires:
            - prd_terraform_fmt_validate
      - prd_terraform_apply:
          filters:
            branches:
              only: master
          requires:
            - prd_terraform_plan
