version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0.0
  slack: circleci/slack@3.4.2

executors:
  docker_build:
    machine:
      docker_layer_caching: true

## Deploy lambda-test
jobs:
  deploy_lambda-test:
    working_directory: ~/app
    executor: docker_build
    steps:
    - checkout
    - aws-cli/setup:
        aws-region: AWS_REGION
        aws-access-key-id: AWS_ACCESS_KEY_ID_STG
        aws-secret-access-key: AWS_SECRET_ACCESS_KEY_STG
        override-installed: true
    - run:
        name : install node 14
        command: |
          curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash - \
          && sudo apt install -y nodejs
    - run:
        name : deploy lambda-test
        command: |
          cd lambda-test/ \
          && npm install \
          && zip -r lambda-test.zip . \
          && aws lambda update-function-code --function-name lambda-test --zip-file fileb://lambda-test.zip
    - slack/status:
        fail_only: true
        mentions: 'here'
        failure_message: 'Error Deploy lambda-test 🚨 \n :innocent: ${CIRCLE_USERNAME}     :branch: ${CIRCLE_BRANCH}'
        webhook: ${SLACK_WEBHOOK}
    - slack/notify:
        title: Stg 👍
        color: '#42f486'
        message: 'lambda-test is deploy OK ✨ \n :grin: ${CIRCLE_USERNAME}   :branch: ${CIRCLE_BRANCH}'
        webhook: ${SLACK_WEBHOOK}

workflows:
  version: 2
  deploy_lambda:
    jobs:
      - deploy_lambda-test:
          filters:
            branches:
              only: master

