version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0.0
  slack: circleci/slack@3.4.2
 
parameters:
  deploy_stg_codebuild:
    type: boolean
    default: false
 
executors:
  docker_build:
    machine:
      docker_layer_caching: true
 
jobs:
  deploy_stg_codebuild:
    working_directory: ~/app
    executor: docker_build
    steps:
    - checkout
    - aws-cli/setup:
        aws-region: AWS_REGION
        aws-access-key-id: AWS_ACCESS_KEY_ID_STG
        aws-secret-access-key: AWS_SECRET_ACCESS_KEY_STG
        override-installed: true
    - run:
        name : fix branch
        command: |
            echo ${CIRCLE_BRANCH} |sed -ri "s/BRANCH_NAME/$CIRCLE_BRANCH/g" ~/project/deploy/deploy_codebuild.sh
    - run:
        name : deploy stg
        command: |
            ~/project/deploy/deploy_codebuild.sh
    - slack/status:
        fail_only: true
        mentions: 'here'
        failure_message: 'Error Deploy Stg🚨 \n :innocent: ${CIRCLE_USERNAME}    :branch: ${CIRCLE_BRANCH}'
        webhook: ${SLACK_WEBHOOK}
    - slack/notify:
        title: Stg
        color: '#42f486'
        message: 'Deploy OK ✨ \n :smile: ${CIRCLE_USERNAME}   :branch: ${CIRCLE_BRANCH}'
        webhook: ${SLACK_WEBHOOK}
 
  deploy_prd_codebuild:
    working_directory: ~/app
    executor: docker_build
    steps:
    - checkout
    - aws-cli/setup:
        aws-region: AWS_REGION
        aws-access-key-id: AWS_ACCESS_KEY_ID_PRD
        aws-secret-access-key: AWS_SECRET_ACCESS_KEY_PRD
        override-installed: true
    - run:
        name : fix branch
        command: |
            echo ${CIRCLE_BRANCH} |sed -ri "s/BRANCH_NAME/$CIRCLE_BRANCH/g" ~/project/deploy/deploy_codebuild.sh
    - run:
        name : deploy prd
        command: |
            ~/project/deploy/deploy_codebuild.sh
    - slack/status:
        fail_only: true
        mentions: 'here'
        failure_message: 'Error Deploy Prd🚨 \n :innocent: ${CIRCLE_USERNAME}    :branch: ${CIRCLE_BRANCH}'
        webhook: ${SLACK_WEBHOOK}
    - slack/notify:
        title: Prd
        color: '#42f486'
        message: 'Deploy OK ✨ \n :smile: ${CIRCLE_USERNAME}   :branch: ${CIRCLE_BRANCH}'
        webhook: ${SLACK_WEBHOOK}
 
workflows:
  version: 2
  deploy_stg:
    when: << pipeline.parameters.deploy_stg_codebuild >>
    jobs:
      - deploy_stg_codebuild
  deploy_prd:
    jobs:
      - deploy_prd_codebuild:
          filters:
            branches:
              only: master
